library(GEOquery)
gse <- getGEO("GSE12589",GSEMatrix=FALSE)
gsmplatforms <- lapply(GSMList(gse),function(x) {Meta(x)$platform_id})
head(gsmplatforms)
probesets <- Table(GPLList(gse)[[1]])$ID
gsmlist = Filter(function(gsm) {Meta(gsm)$platform_id=='GPL6848'},GSMList(gse))
data.matrix <- do.call('cbind',lapply(gsmlist,function(x) 
                                      {tab <- Table(x)
                                       mymatch <- match(probesets,tab$ID_REF)
                                       return(tab$VALUE[mymatch])
                                     }))
data.matrix <- apply(data.matrix,2,function(x) {as.numeric(as.character(x))})
require(Biobase)
rownames(data.matrix) <- probesets
colnames(data.matrix) <- names(gsmlist)
write.csv(data.matrix, "Value_matrix.csv")
a <- read.table("my_subset_probes.txt", sep = "\t", stringsAsFactor = FALSE)
k <- read.csv("Value_matrix.csv", stringsAsFactor = FALSE)
names(a)[1] <- paste("X")
ak <- merge(a, k, by = "X")
write.csv(ak, "My_subset_values.csv")
